import type { Comando } from './tipos'

/**
 * Comandos fixos da paleta. Propostas e automações entram dinamicamente,
 * a partir do que está sendo digitado.
 */
export const CATALOGO: Comando[] = [
  {
    id: 'ir-painel',
    rotulo: 'Ir para o Painel',
    categoria: 'Ir para',
    sinonimos: ['dashboard', 'inicio', 'home', 'visao geral'],
    acoes: [{ tipo: 'navegar', para: '/' }],
  },
  {
    id: 'ir-propostas',
    rotulo: 'Ir para Propostas',
    categoria: 'Ir para',
    sinonimos: ['carteira', 'convenios', 'lista'],
    acoes: [{ tipo: 'navegar', para: '/propostas' }],
  },
  {
    id: 'ir-aprovacoes',
    rotulo: 'Ir para Aprovações',
    categoria: 'Ir para',
    sinonimos: ['fila', 'decisao', 'aprovar', 'gestor'],
    acoes: [{ tipo: 'navegar', para: '/aprovacoes' }],
  },
  {
    id: 'ir-cerebro',
    rotulo: 'Abrir o Cérebro',
    categoria: 'Ir para',
    sinonimos: ['grafo', 'conhecimento', 'mapa mental', 'rede'],
    acoes: [{ tipo: 'navegar', para: '/cerebro' }],
  },
  {
    id: 'ir-assistente',
    rotulo: 'Falar com a Cleo',
    categoria: 'Ir para',
    sinonimos: ['assistente', 'chat', 'perguntar', 'ia'],
    acoes: [{ tipo: 'navegar', para: '/assistente' }],
  },
  {
    id: 'ir-paineis',
    rotulo: 'Meus painéis',
    categoria: 'Ir para',
    sinonimos: ['montar painel', 'widgets', 'blocos'],
    acoes: [{ tipo: 'navegar', para: '/paineis' }],
  },
  {
    id: 'ir-ganho',
    rotulo: 'Ver o antes e depois',
    categoria: 'Apresentação',
    sinonimos: ['ganho', 'economia', 'comparativo', 'tempo'],
    acoes: [{ tipo: 'navegar', para: '/ganho' }],
  },
  {
    id: 'ir-emendas',
    rotulo: 'Ir para Emendas',
    categoria: 'Ir para',
    sinonimos: ['parlamentar', 'deputado', 'senador', 'gabinete', 'rp6', 'rp7', 'bancada'],
    acoes: [{ tipo: 'navegar', para: '/emendas' }],
  },
  {
    id: 'ir-orcamento',
    rotulo: 'Ir para Orçamento',
    categoria: 'Ir para',
    sinonimos: ['empenho', 'dotacao', 'liquidado', 'pago', 'restos a pagar', 'funil', 'dinheiro'],
    acoes: [{ tipo: 'navegar', para: '/orcamento' }],
  },
  {
    id: 'ir-vigencias',
    rotulo: 'Ir para Vigências',
    categoria: 'Ir para',
    sinonimos: ['prazo', 'aditivo', 'prorrogacao', 'vencendo', 'vencimento'],
    acoes: [{ tipo: 'navegar', para: '/vigencias' }],
  },
  {
    id: 'ir-contas',
    rotulo: 'Ir para Prestação de contas',
    categoria: 'Ir para',
    sinonimos: ['inadimplencia', 'inadimplente', 'contas', 'comprovacao', 'bloqueio'],
    acoes: [{ tipo: 'navegar', para: '/contas' }],
  },
  {
    id: 'ir-diligencias',
    rotulo: 'Ir para Diligências',
    categoria: 'Ir para',
    sinonimos: ['oficio', 'complementacao', 'pendencia', 'proponente', 'reiterar'],
    acoes: [{ tipo: 'navegar', para: '/diligencias' }],
  },
  {
    id: 'ir-equipe',
    rotulo: 'Ir para Equipe',
    categoria: 'Ir para',
    sinonimos: ['carga', 'analista', 'carteira', 'distribuicao', 'sobrecarga'],
    acoes: [{ tipo: 'navegar', para: '/equipe' }],
  },
  {
    id: 'ir-ritos',
    rotulo: 'Ir para Ritos',
    categoria: 'Automações',
    sinonimos: ['automacao', 'editor', 'regra', 'gatilho', 'agendamento', 'fila'],
    acoes: [{ tipo: 'navegar', para: '/ritos' }],
  },
  {
    id: 'ir-auditoria',
    rotulo: 'Abrir a trilha de auditoria',
    categoria: 'Ir para',
    sinonimos: ['auditoria', 'log', 'historico', 'quem fez', 'controle', 'tcu'],
    acoes: [{ tipo: 'navegar', para: '/auditoria' }],
  },
  {
    id: 'ir-padroes',
    rotulo: 'Ver padrões da carteira',
    categoria: 'Ir para',
    sinonimos: ['anomalia', 'irmas', 'fracionamento', 'concentracao', 'repetido'],
    acoes: [{ tipo: 'navegar', para: '/padroes' }],
  },
  {
    id: 'ir-minutas',
    rotulo: 'Ir para Minutas',
    categoria: 'Ir para',
    sinonimos: ['modelo', 'documento', 'template'],
    acoes: [{ tipo: 'navegar', para: '/minutas' }],
  },
  {
    id: 'ir-situacao',
    rotulo: 'Abrir a sala de situação',
    categoria: 'Apresentação',
    sinonimos: ['projetor', 'tela cheia', 'parede', 'war room', 'painel de parede'],
    acoes: [{ tipo: 'navegar', para: '/situacao' }],
  },
  {
    id: 'ir-relatorio',
    rotulo: 'Gerar relatório executivo',
    categoria: 'Apresentação',
    sinonimos: ['imprimir', 'documento', 'resumo', 'uma pagina', 'oficio'],
    acoes: [{ tipo: 'navegar', para: '/relatorio' }],
  },
  {
    id: 'ir-comparar',
    rotulo: 'Comparar órgãos e propostas',
    categoria: 'Apresentação',
    sinonimos: ['benchmark', 'lado a lado', 'diferenca'],
    acoes: [{ tipo: 'navegar', para: '/comparar' }],
  },
  {
    id: 'filtro-paradas',
    rotulo: 'Propostas paradas há mais de 30 dias',
    categoria: 'Propostas',
    sinonimos: ['travadas', 'sem andamento', 'atrasadas'],
    acoes: [
      { tipo: 'filtrar-propostas', filtro: { paradaHaDias: 30, ordenarPor: 'parada' } },
    ],
  },
  {
    id: 'filtro-analise',
    rotulo: 'Propostas em análise',
    categoria: 'Propostas',
    sinonimos: ['analise'],
    acoes: [{ tipo: 'filtrar-propostas', filtro: { situacao: ['Em análise'] } }],
  },
  {
    id: 'filtro-maiores',
    rotulo: 'Maiores propostas por valor',
    categoria: 'Propostas',
    sinonimos: ['top', 'ranking', 'valor'],
    acoes: [{ tipo: 'filtrar-propostas', filtro: { ordenarPor: 'valor' } }],
  },
]
